export type User = {
  id: number;
  creationDate: Date;
  emailVerfied: Date;
  token: string;
  name: null | string;
  adminConfirm: true;
  MemberShipExpiryDate: null | Date;
  family: null | string;
  fatherName: null | string;
  phoneNumber: string;
  isMobileVerified: boolean;
  isProfileCompleted: boolean;
  isMembershipPaid: boolean;
  membershipPaidDate: null | Date;
  nationalCode: null | string;
  address: null | string;
  pOstalCode: null | string;
  phoneNumberFamily: null | string;
  birthDay: null | Date;
  cityId: null | number;
  email: null | string;
  password: null | string;
  avatar: null | string;
  rezumeFile: null | string;
  birthDate: Date;
  roles: number[];
  refreeFile: null | string;
  coachFile: null | string;
};
